version: "3.8"
services:
    nodeserver:
        build:
            context: .
        ports:
            - "3000:3000"
        environment:
            - INN_MDB_URI=${INN_MDB_URI}
            - INN_JWT=${INN_JWT}
        volumes:
            - ./public:/usr/src/app/public
        